### ISSUE TITLE
Key Bindings

### ISSUE THREAD

**Issue by jny986** [TablePlus/TablePlus-Windows#30] opened 2019-01-25 00:34 UTC
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    MYSQL 5.7.24
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
    46
3. The steps to reproduce this issue:
    Including more keybindings and a list of keybindings for windows.
   eg keybinding for inserting null, cmd + p equivalent

**Comment by eberkund** [comment] 2019-01-31 17:13
Duplicate of #11

**Comment by huyphams** [comment] 2019-12-12 02:21
It's all supported now. Thanks!

**Closed by huyphams** 2019-12-12 02:21 UTC
