### ISSUE TITLE
NULL as text in column editor

### ISSUE THREAD

**Issue by jenstornell** [TablePlus/TablePlus-Windows#178] opened 2020-01-22 11:55 UTC
1. Which driver: MySQL
2. Which TablePlus build number: 114

## The steps to reproduce this issue

1. Visit a table
1. Klick the column view when a row is selected.
1. On a row it says "NULL" as placeholder text.
1. Edit the value and "NULL" is gone.
1. Erase everything in the field.
1. "NULL" reappears. When entering text again the "NULL" is not a part of the value, not as a placeholder.

![null](https://user-images.githubusercontent.com/927011/72892296-75041c80-3d16-11ea-83e1-0440311c012e.png)

**Comment by rwhirn** [comment] 2020-01-22 22:50
duplicate of #160

**Closed** 2020-05-07 10:43 UTC
Labels: bug, done
