### ISSUE TITLE
Oracle Connection For TablePlus Windows

### ISSUE THREAD

**Issue by justonwater** [TablePlus/TablePlus-Windows#182] opened 2020-01-25 14:24 UTC
It's possible to have the Oracle Connection for TablePlus Windows ?

**Comment by huyphams** [comment] 2021-09-01 07:08
Duplicate of https://github.com/TablePlus/TablePlus-Windows/issues/193

**Closed by huyphams** 2021-09-01 07:08 UTC

**Comment by huyphams** [comment] 2023-09-27 15:32
Hi, we are working on a different product which support Oracle now, it's beta if you have a chance, please try it:
http://boltsql.com/
